// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Ic38ypoER0i_1QVoTcEatTh8F5cf4Tg',
    appId: '1:998412431899:web:c49df96a8ef623dd05bebe',
    messagingSenderId: '998412431899',
    projectId: 'test-1-1e0e5',
    authDomain: 'test-1-1e0e5.firebaseapp.com',
    databaseURL: 'https://test-1-1e0e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-1-1e0e5.appspot.com',
    measurementId: 'G-4HXLJGJ85P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9OQY1FZ1enUnLSe10CPHzfr0W4S3uvLA',
    appId: '1:998412431899:android:7b7c70fceb79517e05bebe',
    messagingSenderId: '998412431899',
    projectId: 'test-1-1e0e5',
    databaseURL: 'https://test-1-1e0e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-1-1e0e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHndibmc2D2MBQJwUE55GFb0Ml7nkxnuo',
    appId: '1:998412431899:ios:d122b74c9e1a8f3305bebe',
    messagingSenderId: '998412431899',
    projectId: 'test-1-1e0e5',
    databaseURL: 'https://test-1-1e0e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-1-1e0e5.appspot.com',
    iosBundleId: 'com.example.userApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHndibmc2D2MBQJwUE55GFb0Ml7nkxnuo',
    appId: '1:998412431899:ios:d122b74c9e1a8f3305bebe',
    messagingSenderId: '998412431899',
    projectId: 'test-1-1e0e5',
    databaseURL: 'https://test-1-1e0e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-1-1e0e5.appspot.com',
    iosBundleId: 'com.example.userApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Ic38ypoER0i_1QVoTcEatTh8F5cf4Tg',
    appId: '1:998412431899:web:e3cc559387f4b57b05bebe',
    messagingSenderId: '998412431899',
    projectId: 'test-1-1e0e5',
    authDomain: 'test-1-1e0e5.firebaseapp.com',
    databaseURL: 'https://test-1-1e0e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-1-1e0e5.appspot.com',
    measurementId: 'G-KWQRGYV9H1',
  );

}